#!/usr/bin/env python3
"""Generate the CarbonSight validation report.

Runs the baseline simulation and compares against reference values,
writing results to docs/validation-report.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from carbonsight.core.engine import ExecutionMode, SimulationConfig, SimulationEngine
from carbonsight.core.graph import SimulationGraph
from carbonsight.data.loaders import load_fleet_inventory, load_survival_curves, load_vmt_by_age
from carbonsight.domain.emissions import compute_production_emissions, compute_usage_emissions
from carbonsight.domain.emissions_nodes import create_emissions_nodes
from carbonsight.domain.fleet_nodes import create_fleet_dynamics_nodes
from carbonsight.domain.macro_drivers import create_macro_driver_nodes
from tests.fixtures.validation_references import (
    EKIDEN_V1_FLEET_SIZE,
    EKIDEN_V1_POWERTRAIN_SHARES_YEAR0,
    EKIDEN_V1_TOTAL_GHG_GRAMS,
    GREET_BEV_75KWH_PRODUCTION_KG,
    GREET_BEV_ANNUAL_USAGE_KG,
    GREET_BEV_PRODUCTION_RANGE,
    GREET_BEV_USAGE_RANGE,
    GREET_ICEV_ANNUAL_USAGE_KG,
    GREET_ICEV_PRODUCTION_KG,
    GREET_ICEV_PRODUCTION_RANGE,
    GREET_ICEV_USAGE_RANGE,
    REGRESSION_GHG_TOLERANCE,
    VISION_FLEET_SIZE_MAX,
    VISION_FLEET_SIZE_MIN,
)


def build_graph():
    fleet = load_fleet_inventory()
    survival = load_survival_curves()
    vmt = load_vmt_by_age()
    graph = SimulationGraph()
    for n in create_fleet_dynamics_nodes(fleet, survival, vmt):
        graph.add_node(n)
    for n in create_emissions_nodes():
        graph.add_node(n)
    for n in create_macro_driver_nodes():
        graph.add_node(n)
    graph.validate()
    return graph


def run_baseline():
    graph = build_graph()
    config = SimulationConfig(
        start_year=2024, num_years=10, execution_mode=ExecutionMode.DETERMINISTIC
    )
    engine = SimulationEngine(graph, config)
    return engine.run(
        overrides={"vmt_adjustment": 1.0, "powertrain_preference_shift": 1.0},
        mode=ExecutionMode.DETERMINISTIC,
    )


def pass_fail(condition):
    return "PASS" if condition else "**FAIL**"


def generate_report():
    print("Running baseline simulation...")
    result = run_baseline()

    lines = []
    lines.append("# CarbonSight Validation Report")
    lines.append("")
    lines.append("**Generated**: Auto-generated by `tests/generate_validation_report.py`")
    lines.append("**Baseline**: 10-year deterministic, macro drivers neutralized")
    lines.append("")

    # --- Section 1: Regression vs Ekiden v1 ---
    lines.append("## 1. Regression Validation vs Ekiden v1")
    lines.append("")
    lines.append("Compares CarbonSight baseline Total GHG against Ekiden v1 output.")
    lines.append("Tolerance: 5% relative (per RPD success criteria).")
    lines.append("")
    lines.append("| Year | CarbonSight (Mt) | Ekiden v1 (Mt) | Delta (%) | Status |")
    lines.append("|------|-----------------|----------------|-----------|--------|")

    for idx, yr in enumerate(result.year_results):
        te = yr.outputs.get("total_emissions", {})
        cs_ghg = te.get("total_ghg", 0) if isinstance(te, dict) else 0
        ekiden_ghg = EKIDEN_V1_TOTAL_GHG_GRAMS[idx]
        pct = (cs_ghg - ekiden_ghg) / ekiden_ghg * 100 if ekiden_ghg else 0
        status = pass_fail(abs(pct) <= REGRESSION_GHG_TOLERANCE * 100)
        lines.append(
            f"| {yr.year} | {cs_ghg / 1e9:.1f} | {ekiden_ghg / 1e9:.1f} | {pct:+.1f}% | {status} |"
        )

    lines.append("")

    # Fleet size
    lines.append("### Fleet Size Trajectory")
    lines.append("")
    lines.append("| Year | CarbonSight | Ekiden v1 | Delta (%) |")
    lines.append("|------|-------------|-----------|-----------|")

    for idx, yr in enumerate(result.year_results):
        fs = yr.outputs.get("fleet_snapshot", {})
        cs_total = fs.get("total_vehicles", 0) if isinstance(fs, dict) else 0
        ekiden_total = EKIDEN_V1_FLEET_SIZE.get(idx, 0)
        pct = (cs_total - ekiden_total) / ekiden_total * 100 if ekiden_total else 0
        lines.append(f"| {yr.year} | {cs_total:,.0f} | {ekiden_total:,.0f} | {pct:+.1f}% |")

    lines.append("")

    # Powertrain mix
    lines.append("### Powertrain Stock Shares (Year 0)")
    lines.append("")
    lines.append("| Powertrain | CarbonSight | Ekiden v1 | Delta (pp) |")
    lines.append("|------------|-------------|-----------|------------|")

    yr0 = result.year_results[0]
    fs0 = yr0.outputs.get("fleet_snapshot", {})
    by_pt = fs0.get("by_powertrain", {}) if isinstance(fs0, dict) else {}
    total = fs0.get("total_vehicles", 1) if isinstance(fs0, dict) else 1
    for pt in ["icev", "hev", "phev", "bev"]:
        cs_share = by_pt.get(pt, 0) / total * 100 if total > 0 else 0
        ekiden_share = EKIDEN_V1_POWERTRAIN_SHARES_YEAR0.get(pt, 0) * 100
        delta = cs_share - ekiden_share
        lines.append(f"| {pt.upper()} | {cs_share:.1f}% | {ekiden_share:.1f}% | {delta:+.1f} |")

    lines.append("")

    # --- Section 2: GREET Spot Checks ---
    lines.append("## 2. GREET 2024 Lifecycle Spot Checks")
    lines.append("")
    lines.append("Per-vehicle emissions compared against GREET 2024 published values.")
    lines.append("")

    # ICEV production
    icev_fleet = pd.DataFrame(
        [
            {
                "age": 0,
                "powertrain": "icev",
                "n": 1,
                "batt_kwh": 0,
                "mpg": 25.0,
                "mpge": float("inf"),
                "vmt": 12000,
                "vmt_bucket": "high",
            }
        ]
    )
    icev_prod = compute_production_emissions(icev_fleet)["production_ghg"].sum()

    # BEV production
    bev_fleet = pd.DataFrame(
        [
            {
                "age": 0,
                "powertrain": "bev",
                "n": 1,
                "batt_kwh": 75.0,
                "mpg": float("inf"),
                "mpge": 100.0,
                "vmt": 12000,
                "vmt_bucket": "high",
            }
        ]
    )
    bev_prod = compute_production_emissions(bev_fleet)["production_ghg"].sum()

    # ICEV usage
    icev_use_fleet = pd.DataFrame(
        [
            {
                "age": 1,
                "powertrain": "icev",
                "n": 1,
                "batt_kwh": 0,
                "mpg": 25.0,
                "mpge": float("inf"),
                "vmt": 12000,
                "vmt_bucket": "high",
            }
        ]
    )
    icev_use = compute_usage_emissions(icev_use_fleet)["use_ghg"].sum()

    # BEV usage
    bev_use_fleet = pd.DataFrame(
        [
            {
                "age": 1,
                "powertrain": "bev",
                "n": 1,
                "batt_kwh": 75.0,
                "mpg": float("inf"),
                "mpge": 100.0,
                "vmt": 12000,
                "vmt_bucket": "high",
            }
        ]
    )
    bev_use = compute_usage_emissions(bev_use_fleet)["use_ghg"].sum()

    lines.append("| Metric | CarbonSight | GREET Reference | GREET Range | Status |")
    lines.append("|--------|-------------|-----------------|-------------|--------|")
    lines.append(
        f"| ICEV Production | {icev_prod:,.0f} kg | {GREET_ICEV_PRODUCTION_KG:,} kg | {GREET_ICEV_PRODUCTION_RANGE} | {pass_fail(GREET_ICEV_PRODUCTION_RANGE[0] <= icev_prod <= GREET_ICEV_PRODUCTION_RANGE[1])} |"
    )
    lines.append(
        f"| BEV Production (75 kWh) | {bev_prod:,.0f} kg | {GREET_BEV_75KWH_PRODUCTION_KG:,} kg | {GREET_BEV_PRODUCTION_RANGE} | {pass_fail(GREET_BEV_PRODUCTION_RANGE[0] <= bev_prod <= GREET_BEV_PRODUCTION_RANGE[1])} |"
    )
    lines.append(
        f"| ICEV Annual Usage | {icev_use:,.0f} kg | {GREET_ICEV_ANNUAL_USAGE_KG:,} kg | {GREET_ICEV_USAGE_RANGE} | {pass_fail(GREET_ICEV_USAGE_RANGE[0] <= icev_use <= GREET_ICEV_USAGE_RANGE[1])} |"
    )
    lines.append(
        f"| BEV Annual Usage | {bev_use:,.0f} kg | {GREET_BEV_ANNUAL_USAGE_KG:,} kg | {GREET_BEV_USAGE_RANGE} | {pass_fail(GREET_BEV_USAGE_RANGE[0] <= bev_use <= GREET_BEV_USAGE_RANGE[1])} |"
    )

    lines.append("")

    # --- Section 3: VISION Spot Checks ---
    lines.append("## 3. VISION Fleet Spot Checks")
    lines.append("")

    fleet_sizes = []
    for yr in result.year_results:
        fs = yr.outputs.get("fleet_snapshot", {})
        fleet_sizes.append(fs.get("total_vehicles", 0) if isinstance(fs, dict) else 0)

    fleet_in_range = all(VISION_FLEET_SIZE_MIN <= s <= VISION_FLEET_SIZE_MAX for s in fleet_sizes)

    yr0_fs = result.year_results[0].outputs.get("fleet_snapshot", {})
    yr_last_fs = result.year_results[-1].outputs.get("fleet_snapshot", {})
    bev0 = (
        yr0_fs.get("by_powertrain", {}).get("bev", 0) / yr0_fs.get("total_vehicles", 1)
        if isinstance(yr0_fs, dict)
        else 0
    )
    bev_last = (
        yr_last_fs.get("by_powertrain", {}).get("bev", 0) / yr_last_fs.get("total_vehicles", 1)
        if isinstance(yr_last_fs, dict)
        else 0
    )

    lines.append("| Metric | Result | Reference | Status |")
    lines.append("|--------|--------|-----------|--------|")
    lines.append(
        f"| Fleet size range | {min(fleet_sizes):,.0f} – {max(fleet_sizes):,.0f} | {VISION_FLEET_SIZE_MIN:,} – {VISION_FLEET_SIZE_MAX:,} | {pass_fail(fleet_in_range)} |"
    )
    lines.append(
        f"| BEV share growth | {bev0 * 100:.1f}% → {bev_last * 100:.1f}% | Increases over time | {pass_fail(bev_last > bev0)} |"
    )

    lines.append("")

    # --- Section 4: Sources ---
    lines.append("## 4. Sources")
    lines.append("")
    lines.append("| Source | Version | Used For |")
    lines.append("|--------|---------|----------|")
    lines.append("| Ekiden v1 (TRI) | 2024 | Regression baseline trajectory |")
    lines.append("| Argonne GREET Model | 2024 | Per-vehicle lifecycle emission factors |")
    lines.append(
        "| Argonne VISION Model | 2024 Reference Case | Fleet size and composition projections |"
    )
    lines.append("| EPA Multi-Pollutant Standards | MY2027+ | Powertrain proportion assumptions |")
    lines.append("| NHTS | 2017 | VMT by vehicle age |")
    lines.append("| Greene & Leard | 2024 | Vehicle survival/scrappage curves |")
    lines.append("| EIA AEO | 2024 | Oil/electricity price trajectories |")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by CarbonSight validation suite*")

    report = "\n".join(lines)
    output_path = Path(__file__).parent.parent / "docs" / "validation-report.md"
    output_path.write_text(report)
    print(f"Report written to {output_path}")
    return report


if __name__ == "__main__":
    generate_report()
